## Parameter values common to all scenarios
cost_values:
  carbon_price: 1.0 # €/kgCO2
  solar_capex: 1000.0 # €/kWp
  solar_lifetime: 20 # years
  solar_opex: 10 # €/kWp/year
  wind_capex: 5000.0 # €/kWp
  wind_lifetime: 20 # years
  wind_opex: 100 # €/kWp/year
timeseries_values:
  carbon_year: 2023
  price_year: 2023
storage_values:
  CAES:
    discharge_ratio: 0.1 # kWp/kWh
    depth_of_discharge: 0.4
  Li-ion:
    discharge_ratio: 2 # kWp/kWh
    depth_of_discharge: 0.9
  Pb-acid:
    discharge_ratio: 5 # kWp/kWh
    depth_of_discharge: 0.5
  VRBF:
    discharge_ratio: 0.5 # kWp/kWh
    depth_of_discharge: 1.0
  # PCM:
  #   discharge_ratio: 0.05 # kWp/kWh