## Common model & probability settings for all experiments

# Directories and file patterns
dataset_dir: [data, processed]
results_dir: [results]

# Available years of data
wind_years: &wind_years [2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
solar_years: &solar_years [2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
price_years: [2023]
carbon_years: [2023]

# Location of assets
site_location: [51.95,4.1]
wind_location: [52.7,3.5]

# Default energy model settings
model_settings:
  T: 8760
  initial_SoC: 0.5
  max_storage_cap: 1.0e+9 # slack bound
  grid_capacity: 500.0e+3 # kW
  capex_budget: 5.0e+8 # €/yr (10e9/20)
  solar_capacity_limit: 500.0e+3 # kWp
  N_technologies: 1
  allow_elec_purchase: True
  use_CVaR: False
  CVaR_alpha: 0.1 # TODO: confirm
  CVaR_beta: 1 # TODO: confirm

# Probabilistic model settings
probability_settings: # tuples are [mu,sigma]
  TODO: ...
  measurement_sigma_reduction: 0.25 # TODO: confirm
  load_level: [250000,25000]
  wind_years: *wind_years
  solar_years: *solar_years
  li-ion: # TODO: work out distributions
    cost: []
    lifetime: []
    efficiency: []