## Settings for experiment with price and carbon data from 2024

adopt: base

scenarios_dir: [scenarios, data24]
results_dir: [results, data24]

probability_settings:
  price_year: 2024
  carbon_year: 2024