# Model settings for experiments with 2 storage technologies

adopt: base

results_dir: [results, two_techs]

model_settings:
  N_technologies: 2

solver_settings:
  TimeLimit: 6840 # (s), 2hrs with 5% buffer